# Generated by Django 5.0.1 on 2024-05-04 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_imagecollection_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagecollection',
            name='cover_image',
            field=models.ImageField(upload_to='collections'),
        ),
    ]
