# Generated by Django 5.0.1 on 2024-05-04 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_imagecollection_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationalarticle',
            name='category',
            field=models.CharField(choices=[('Career Development', 'Career Development'), ('Personal Growth and Development', 'Personal Growth and Development'), ('Leadership & Entrepreneurship', 'Leadership & Entrepreneurship'), ('Financial Literacy', 'Financial Literacy'), ('Social Impact', 'Social Impact'), ('Health and Wellness', 'Health and Wellness'), ('Technology & Innovation', 'Technology & Innovation')], max_length=255),
        ),
    ]
